name: INVO App Release

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master
jobs:
  Build_Android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Update version in pubspec.yaml
        run: |
          VERSION_NAME="1.0.${{ github.run_number }}"
          VERSION_CODE=${{ github.run_number }}
          sed -i "s/^version: .*/version: $VERSION_NAME+$VERSION_CODE/" pubspec.yaml
          echo "Updated version to $VERSION_NAME+$VERSION_CODE"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Android APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.TOKEN }}
          tag: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Automatically generated release from GitHub Actions.
          draft: false
          prerelease: false

        # Delete older releases, keep only the latest 3
      - name: Delete old releases (keep last 3)
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
